- name: Demonstrate CMDB management
  hosts: 192.168.101.9
  gather_facts: false

  tasks:
    - name: Simulate VM creation
      ansible.builtin.set_fact:
        instance:
          name: debian-aap
          id: 1555677392985251426
          public_ip_address: 192.168.101.9

    - name: Register the newly-created VM instance
      servicenow.itsm.configuration_item:
        name: "{{ instance.name }}"
        sys_class_name: cmdb_ci_vm_instance
        ip_address: "{{ instance.public_ip_address }}"
        other:
          vm_inst_id: "{{ instance.id }}"